[agent]
uid = unique-id-2283469
server_uri = http://xdev.arkcom.ru:9999/app/webagent1/api
task_interval = 30
tasks_dir = tasks
results_dir = results
access_code = 045ab2-9504-91be-fd8f-60fe1d54
log_level = info

[client]
uid = unique-id-2283469
server_uri = http://xdev.arkcom.ru:9999/app/webagent1/api
access_code = 045ab2-9504-91be-fd8f-60fe1d54
log_level = info
